name: Print OS Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # macOS version
      - name: Show macOS version
        if: runner.os == 'macOS'
        run: sw_vers

      # Ubuntu version
      - name: Show Ubuntu version
        if: runner.os == 'Linux'
        run: cat /etc/os-release

      # Windows version
      - name: Show Windows version
        if: runner.os == 'Windows'
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
